import type { MatchingDimension } from "../scoring/dimensions";
import type { AssessmentFeatureVector } from "../types/assessment-input";
import type { BusinessCandidate } from "../types/business-candidate";

/**
 * Five rule categories, as specified:
 *  - required:  must pass, or the candidate is excluded outright
 *  - preferred: contributes positively when it passes, no penalty when it doesn't
 *  - bonus:     adds to the score when it passes; never subtracts
 *  - penalty:   subtracts from the score when it fails; never adds
 *  - exclusion: if it matches, the candidate is removed regardless of score
 *  - aiGenerated: same shape as any other rule, but authored by a future
 *    AI process rather than a human — kept as its own type so results can
 *    be filtered/audited by provenance (e.g. "show me only human-authored
 *    rules that fired").
 */
export enum RuleType {
  Required = "required",
  Preferred = "preferred",
  Bonus = "bonus",
  Penalty = "penalty",
  Exclusion = "exclusion",
  AIGenerated = "aiGenerated",
}

export type RuleOperator = "gte" | "lte" | "eq" | "neq" | "in" | "notIn";

/**
 * One condition within a rule. Deliberately data (dimension + operator +
 * value), not a function — the same reasoning as
 * `BusinessQuestionWeight` in the Business Engine: a rule that's data can
 * be authored by an admin UI, generated by an AI process, or A/B tested,
 * without a code change.
 */
export interface RuleCondition {
  dimension: MatchingDimension;
  operator: RuleOperator;
  value: number | string | string[];
}

/**
 * A complete matching rule. No rule instances exist yet — see
 * ./rule-registry.ts, which exports an intentionally empty list.
 */
export interface MatchingRule {
  id: string;
  type: RuleType;
  /** Translation key for a human-readable explanation of this rule, for the "why this match" UI. */
  translationKey: string;
  /** All conditions must hold (AND) for the rule to "pass". Composing OR/NOT is a future extension, not implemented here. */
  conditions: RuleCondition[];
  /**
   * How much this rule adds to (bonus) or subtracts from (penalty) the
   * overall score when it fires. Unused for required/exclusion rules,
   * which are pass/fail rather than score-adjusting.
   */
  scoreImpact?: number;
  isActive: boolean;
}

export interface RuleEvaluationContext {
  assessmentFeatures: AssessmentFeatureVector;
  candidate: BusinessCandidate;
}

export interface RuleEvaluationResult {
  rule: MatchingRule;
  passed: boolean;
  /** The actual score adjustment applied, after accounting for rule type (e.g. a failed "bonus" rule always adjusts by 0). */
  scoreAdjustment: number;
}
